### PR TITLE
Improve documentation and add example

### PR DESCRIPTION
**Pull request by faern**
Add some much needed documentation. Still far from covering the entire API surface. But still a lot better than before.

Also adding a quite verbose and explaining example. It shows, step by step, how to add a table, chains and two rules. Has lots of comments for each step.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/17)

### CODE REVIEW

**Review by jvff — COMMENTED** [review]
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/17)* status: 8 of 13 files reviewed, all discussions resolved (waiting on @jvff)

**Review by jvff — COMMENTED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/17)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @jvff and @faern)

___
*[nftnl/src/rule.rs, line 59 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/17#-LMh1LLCAKZHKwVa6N9C:-LMh1LLCAKZHKwVa6N9D:b8urfqf) ([raw file](https://github.com/mullvad/nftnl-rs/blob/1d44ebee8f6266a640fd8b7fdf0373f68144a554/nftnl/src/rule.rs#L59)):*
> ```Rust
>     /// Adds an expression to this rule. Expressions are evaluated from first to last added.
>     /// As soon as an expression does not match the packet it's being evaluated for, evaluation
>     /// stops and the packet is being evaluated against the next rule in the chain.
> ```

I think the `being` is unnecessary here?

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/17)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @jvff and @faern)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/17)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[nftnl/src/rule.rs, line 59 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/17#-LMh1LLCAKZHKwVa6N9C:-LMh3cZX-7ixpjOIF8gJ:b-896fix) ([raw file](https://github.com/mullvad/nftnl-rs/blob/1d44ebee8f6266a640fd8b7fdf0373f68144a554/nftnl/src/rule.rs#L59)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think the `being` is unnecessary here?
</blockquote></details>

Done.

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/17)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[nftnl/examples/add-rules.rs, line 11 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/17#-LMhJ_g-0pRZIX-A1Yba:-LMhJ_g07SJpS5rQoDSh:b57bgzb) ([raw file](https://github.com/mullvad/nftnl-rs/blob/1d44ebee8f6266a640fd8b7fdf0373f68144a554/nftnl/examples/add-rules.rs#L11)):*
> ```Rust
> //! executed as root:
> //! ```bash
> //! $ nft list ruleset
> ```

Maybe change the `$` to `#` to make it look like a root shell? Not sure if it gets ignored by `rustdoc` though :(
___
*[nftnl/examples/add-rules.rs, line 126 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/17#-LMhQQJvCsdlUDRWSNpa:-LMhQQJwBgQqj9F1dFFq:blfv440) ([raw file](https://github.com/mullvad/nftnl-rs/blob/1d44ebee8f6266a640fd8b7fdf0373f68144a554/nftnl/examples/add-rules.rs#L126)):*
> ```Rust
>     // protocol the packet being processed is using.
>     block_out_to_private_net_rule.add_expr(&nft_expr!(meta nfproto))?;
>     // Check so the currently processed packet is an IPv4 packet. This must be done before payload
> ```

I think `so` could be `if`?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/17)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[nftnl/examples/add-rules.rs, line 11 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/17#-LMhJ_g-0pRZIX-A1Yba:-LMjIGYL9Y6TeT7vemew:b-ovcibi) ([raw file](https://github.com/mullvad/nftnl-rs/blob/1d44ebee8f6266a640fd8b7fdf0373f68144a554/nftnl/examples/add-rules.rs#L11)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Maybe change the `$` to `#` to make it look like a root shell? Not sure if it gets ignored by `rustdoc` though :(
</blockquote></details>

Good idea. Not sure what you mean by "ignored by rustdoc" Ignored in what way? Syntax highlighting? I have not even looked at the generated docs for this, since it's in an example and not the library, I'm not even entirely sure docs are generated ever for this :thinking: 
___
*[nftnl/examples/add-rules.rs, line 126 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/17#-LMhQQJvCsdlUDRWSNpa:-LMjI1GW21rXhVt2z289:b-896fix) ([raw file](https://github.com/mullvad/nftnl-rs/blob/1d44ebee8f6266a640fd8b7fdf0373f68144a554/nftnl/examples/add-rules.rs#L126)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think `so` could be `if`?
</blockquote></details>

Done.

**Review by jvff — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/17)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[nftnl/examples/add-rules.rs, line 11 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/17#-LMhJ_g-0pRZIX-A1Yba:-LMl6xN_BvvnKH0zUGtQ:b-r6js9h) ([raw file](https://github.com/mullvad/nftnl-rs/blob/1d44ebee8f6266a640fd8b7fdf0373f68144a554/nftnl/examples/add-rules.rs#L11)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Good idea. Not sure what you mean by "ignored by rustdoc" Ignored in what way? Syntax highlighting? I have not even looked at the generated docs for this, since it's in an example and not the library, I'm not even entirely sure docs are generated ever for this :thinking: 
</blockquote></details>

In rustdoc tests you can start a line with `#`, which will make the line execute but not appear in the documentation. I'm not sure if there is a similar behavior for non-rustdoc tests, though.

**Pull request merged**
