### PR TITLE
Add set and lookup

### PR DESCRIPTION
**Pull request by faern**
Adding the `Set` type that is a collection of values one can use in rules. Combined with the `Lookup` expression one can build rules kind of like `ip saddr in { 10.0.0.3, 10.0.0.9 } drop` to drop all packets from those two addresses.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[nftnl/src/set.rs, line 124 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LCgXBMj2W-7RjOui7x_:-LCgXBMj2W-7RjOui7xa:b-79uqpx) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L124)):*
> ```Rust
>             type_ as u16,
>             self.table.get_family() as u16,
>             (libc::NLM_F_APPEND | libc::NLM_F_CREATE | libc::NLM_F_ACK) as u16,
> ```

I honestly have no idea which of these `NLM_F_*` flags should be present in which implementation of `NlMsg`. I have taken inspiration from examples here and there and the code in `nftables`. It's very likely that they should not be hardcoded, but vary on some condition. But at least it has worked with these for the scenarios I have tested out.

---

*[nftnl/src/expr/lookup.rs, line 44 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LCgXVRI8ds9nKA_Gfts:-LCgXVRI8ds9nKA_Gftt:bbzcjqf) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/expr/lookup.rs#L44)):*
> ```Rust
>             // if self.reverse {
>             // sys::nftnl_expr_set_u32(expr, sys::NFTNL_EXPR_LOOKUP_FLAGS as u16,
>             // libc::NFT_LOOKUP_F_INV as u32); }
> ```

Not very nice to have commented out code, I know. But I have been experimenting with this expression and I don't think I'm done with it. When we are done merging this library and start using it more in the VPN client I suspect will will hit problems and have to go improve this library. Then it's good if we have some experimenting code left so it become easy to start doing that again. Or do you want me to remove it for now?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by pinkisemils** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[nftnl/src/set.rs, line 23 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChW-naD5FlHxaBPEf8:-LChW-naD5FlHxaBPEf9:b-umwupb) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L23)):*
> ```Rust
>         let mut set = nft_set!{$name, $id, $table, $family}.expect("Set allocation failed");
>         $(
>             set.add($value).expect("Unable to add to set in macro");
> ```

Maybe you should specify which 

---

*[nftnl/src/expr/lookup.rs, line 44 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LCgXVRI8ds9nKA_Gfts:-LChaDGPBelqC9FhfeR6:bak61jz) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/expr/lookup.rs#L44)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Not very nice to have commented out code, I know. But I have been experimenting with this expression and I don't think I'm done with it. When we are done merging this library and start using it more in the VPN client I suspect will will hit problems and have to go improve this library. Then it's good if we have some experimenting code left so it become easy to start doing that again. Or do you want me to remove it for now?
</blockquote></details>

If you left a comment above it explaining itself, then I'd be ok with leaving it in :wink: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by pinkisemils** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[nftnl/src/set.rs, line 23 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChW-naD5FlHxaBPEf8:-LChaf1tCcW5Cxm8wfSR:bl8oxk2) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L23)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Maybe you should specify which 
</blockquote></details>

Disregard this comment, originally I wanted to see if the string in `expect()` could refer to the name of the macro in which this fails, but subsequently realised that this macro can  be invoked several levels deep into a macro call stack. What I didn't do is remove the comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by jvff** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[nftnl/src/set.rs, line 18 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChb-33DEESkVfRH-fj:-LChb-33DEESkVfRH-fk:b-napmw) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L18)):*
> ```Rust
>     };
>     ($name:expr, $id:expr, $table:expr, $family:expr; { }) => {
>         nft_set!{$name, $id, $table, $family}
> ```

Looks weird to me to have a single line macro using `{}`s. Can't it use `();` instead?

---

*[nftnl/src/set.rs, line 23 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChW-naD5FlHxaBPEf8:-LChbIjL7mpiP3xalnyt:bwmqe9e) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L23)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Disregard this comment, originally I wanted to see if the string in `expect()` could refer to the name of the macro in which this fails, but subsequently realised that this macro can  be invoked several levels deep into a macro call stack. What I didn't do is remove the comment.
</blockquote></details>

Would this work?:

```
.expect(stringify!(Unable to add $value to set $name));
```

---

*[nftnl/src/set.rs, line 64 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LCheI59DBtGzmwtOrSm:-LCheI59DBtGzmwtOrSn:b-giyzq1) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L64)):*
> ```Rust
>                 _marker: ::std::marker::PhantomData,
>             };
>             Ok(this)
> ```

Can't this line be merged with the previous binding? That would lead to `Ok(Set{ .. })`

---

*[nftnl/src/set.rs, line 98 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChf0Ty-oHrBInGUEAU:-LChf0Ty-oHrBInGUEAV:b-krhlos) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L98)):*
> ```Rust
>     }
> 
>     pub fn get_family(&self) -> ProtoFamily {
> ```

I think the general convention for getter methods is to not have the `get_` prefix. That said, I think it could be a good idea to keep the prefix when the getter method has to do some complex operation (or a foreign call). What do you think?

---

*[nftnl/src/expr/lookup.rs, line 44 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LCgXVRI8ds9nKA_Gfts:-LChaCPm7z7f5DsReAM_:bw0ky2m) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/expr/lookup.rs#L44)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Not very nice to have commented out code, I know. But I have been experimenting with this expression and I don't think I'm done with it. When we are done merging this library and start using it more in the VPN client I suspect will will hit problems and have to go improve this library. Then it's good if we have some experimenting code left so it become easy to start doing that again. Or do you want me to remove it for now?
</blockquote></details>

I usually leave this kind of stuff in local branches/tags, but now that you've touched the subject, I'm a little worried my approach might lead to lost code because there's no backup :( I'm going to do a backup just in case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[nftnl/src/set.rs, line 23 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChW-naD5FlHxaBPEf8:-LChjAD-A6r9RmNbJFFk:b92lqc5) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L23)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Would this work?:

```
.expect(stringify!(Unable to add $value to set $name));
```
</blockquote></details>

Fixed. However, `$value` and `$name` will just expand to their variable names if the macro is called as `nft_set!{my_set_name, ...}` etc, not the actual name of the set. But better than nothing I guess.

---

*[nftnl/src/set.rs, line 64 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LCheI59DBtGzmwtOrSm:-LChjtyJ6VRED9VdoqGN:bcsip8g) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L64)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Can't this line be merged with the previous binding? That would lead to `Ok(Set{ .. })`
</blockquote></details>

Yes it can.. I have no idea why this is left. I guess I created `this` higher up in some older version of this code. Good spot.

---

*[nftnl/src/set.rs, line 98 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChf0Ty-oHrBInGUEAU:-LChk4XJ81BQvqxFCQ_4:b-r6w478) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L98)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think the general convention for getter methods is to not have the `get_` prefix. That said, I think it could be a good idea to keep the prefix when the getter method has to do some complex operation (or a foreign call). What do you think?
</blockquote></details>

Hmm.. In general I agree with you on this. However, we have already merged a lot of `get_name` and `get_family` etc in the `Chain`/`Table`/`Rule` types. So I don't think this is the place and time to change. Then better get all the features in and if we don't like `get_` then we create one PR that removes all of them afterwards?

---

*[nftnl/src/expr/lookup.rs, line 44 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LCgXVRI8ds9nKA_Gfts:-LChkPDw5UV-MeZj_ULk:bd3ia73) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/expr/lookup.rs#L44)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I usually leave this kind of stuff in local branches/tags, but now that you've touched the subject, I'm a little worried my approach might lead to lost code because there's no backup :( I'm going to do a backup just in case.
</blockquote></details>

Good that my comment triggered you to take a backup :wink: 
I'll leave a comment explaining why the comment is there!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by faern** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[nftnl/src/set.rs, line 18 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChb-33DEESkVfRH-fj:-LChkrbB0R7beUPeJWsz:b-4ucsld) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L18)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Looks weird to me to have a single line macro using `{}`s. Can't it use `();` instead?
</blockquote></details>

It's supposed to represent a list (or a set more specifically) so IMO the best chars would be to use `[]`. Is that better than `{}`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by jvff** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[nftnl/src/set.rs, line 18 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChb-33DEESkVfRH-fj:-LChnYRN4oOUJBgaYyiX:b-pfy7j1) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It's supposed to represent a list (or a set more specifically) so IMO the best chars would be to use `[]`. Is that better than `{}`?
</blockquote></details>

I was actually referring to the `nft_set!{$name, $id, $table, $family}` line. I think for the set elements you can keep the `{}`.

---

*[nftnl/src/set.rs, line 98 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChf0Ty-oHrBInGUEAU:-LCho1VL7yx0qEBzQ9vb:b-g18etk) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L98)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Hmm.. In general I agree with you on this. However, we have already merged a lot of `get_name` and `get_family` etc in the `Chain`/`Table`/`Rule` types. So I don't think this is the place and time to change. Then better get all the features in and if we don't like `get_` then we create one PR that removes all of them afterwards?
</blockquote></details>

Ok, that sounds reasonable.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by jvff** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[nftnl/src/set.rs, line 23 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChoFOi8niIaJ1krdCT:-LChoFOi8niIaJ1krdCU:bnvsivh) ([raw file](https://github.com/mullvad/nftnl-rs/blob/c726aee164e161a2c3b11f7a8571d326ae9a648c/nftnl/src/set.rs#L23)):*
> ```Rust
>         let mut set = nft_set!{$name, $id, $table, $family}.expect("Set allocation failed");
>         $(
>             set.add($value).expect(stringify!("Unable to add $value to set $name"));
> ```

Are the `"`s necessary? Won't they prevent the expansion?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by faern** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[nftnl/src/set.rs, line 18 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChb-33DEESkVfRH-fj:-LChvGbj2FpxGNvrw5bd:b-4yhv0o) ([raw file](https://github.com/mullvad/nftnl-rs/blob/52c5db94b6cda96cebe32c9564d7cf38918240d3/nftnl/src/set.rs#L18)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I was actually referring to the `nft_set!{$name, $id, $table, $family}` line. I think for the set elements you can keep the `{}`.
</blockquote></details>

Ah, ok. Changed that. But kept the `[]` brackets fro defining the set as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by faern** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[nftnl/src/set.rs, line 23 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/6#-LChoFOi8niIaJ1krdCT:-LChvR9v1Hv3K19ZPmIf:b-rl1dgq) ([raw file](https://github.com/mullvad/nftnl-rs/blob/c726aee164e161a2c3b11f7a8571d326ae9a648c/nftnl/src/set.rs#L23)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Are the `"`s necessary? Won't they prevent the expansion?
</blockquote></details>

Yeah maybe. Now they are removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Comment by jvff** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/6)*

**Pull request merged**
