### PR TITLE
Add ffi bindings to libnftnl

### PR DESCRIPTION
**Pull request by faern**
Adding helper scripts for FFI code generation and the bindings for libnftnl versions 1.0.6 through 1.0.9.

Sorry for HUGE PR, but most of the code is generated and does not need manual review of course. If you want to verify it you could install the same bindgen version as me (0.36) and try to generate the same thing yourselves.

Reason for 1.0.6 through 1.0.9 is that Ubuntu has 1.0.7, so we need to support at least that old, and I added one more for safety. Then I want to support everything up to the latest. But with this layout it's easy to add new versions. Just run the `generate_bindings.sh` script towards a new version, add a feature for it and a few conditional compilation statements.

The thought with the features is that each feature should activate all older features as well.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)

### CODE REVIEW

**Comment by jvff** [comment]
Reviewed 4 of 9 files at r1.
Review status: 4 of 9 files reviewed at latest revision, all discussions resolved.

---

*[nftnl-sys/generate_bindings.sh, line 42 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmUDfVEjkVhbQVdmDd:-LAmUDfVEjkVhbQVdmDe:b3zvvum) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L42)):*
> ```Shell
> # Manually change struct bodies to (c_void);
> #   Search regex: {\n +_unused: \[u8; 0],\n}
> #   Replace string: (c_void);\n
> ```

If I understood correctly, this is done manually? Can't this be done with `sed`?

---

*[nftnl-sys/generate_bindings.sh, line 46 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmULbc7fbmk4hEnrwo:-LAmULbc7fbmk4hEnrwp:bciuwzr) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L46)):*
> ```Shell
> # Remove all }\nextern "C" { to condense code a bit
> #   Search regex: }\nextern "C" {
> #   Replace string: 
> ```

Same as above, shouldn't `sed` be used here?

---

*[nftnl-sys/generate_bindings.sh, line 48 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmUPeJ5VdfOgPt-cWV:-LAmUPeJ5VdfOgPt-cWW:bk8ohun) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L48)):*
> ```Shell
> #   Replace string: 
> 
> # Add bindgen version to comment at start of file
> ```

Same as above, maybe something like

```
bindgen --version | sed -e 's,^,// ,' > /tmp/bindgen_version.txt
sed -i -e '1{
    i // Code generated by bindgen
    i //
    r /tmp/bingen_version.txt
}' "$BINDING_PATH"
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by jvff** [comment]
*[nftnl-sys/generate_bindings.sh, line 48 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmUPeJ5VdfOgPt-cWV:-LAmlC8Q6j6sYAi-T_hG:b-y6wrpf) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L48)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Same as above, maybe something like

```
bindgen --version | sed -e 's,^,// ,' > /tmp/bindgen_version.txt
sed -i -e '1{
    i // Code generated by bindgen
    i //
    r /tmp/bingen_version.txt
}' "$BINDING_PATH"
```
</blockquote></details>

Simplified: `nftnl-sys]$ sed -i -e "1s/bindgen\$/$(bindgen --version)/" "$BINDING_PATH"`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by faern** [comment]
Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[nftnl-sys/generate_bindings.sh, line 42 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmUDfVEjkVhbQVdmDd:-LAmq7Bw6tFVO_lzlo_c:b8mklzc) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L42)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

If I understood correctly, this is done manually? Can't this be done with `sed`?
</blockquote></details>

Correct. `sed` is not very good with multi line replaces. It should be possible, but rather cumbersome. If you know a good way I'm open for suggestions :)

---

*[nftnl-sys/generate_bindings.sh, line 48 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmUPeJ5VdfOgPt-cWV:-LAmrNi5-6qg3eCDpGTA:boyexb3) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L48)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Simplified: `nftnl-sys]$ sed -i -e "1s/bindgen\$/$(bindgen --version)/" "$BINDING_PATH"`
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by jvff** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[nftnl-sys/generate_bindings.sh, line 42 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmUDfVEjkVhbQVdmDd:-LAn59qhAvUlv6bkY7kN:b4sukyi) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L42)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Correct. `sed` is not very good with multi line replaces. It should be possible, but rather cumbersome. If you know a good way I'm open for suggestions :)
</blockquote></details>

Ok, here's the solution I found:

```
sed -i -e '/^pub struct .* {$/ {
    N;N
    s/ {\n *_unused: \[u8; 0\],\n}/(c_void);\n/
}' "$BINDING_PATH"
```

---

*[nftnl-sys/generate_bindings.sh, line 46 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmULbc7fbmk4hEnrwo:-LAn5QenElfKAFNqEaa9:bax9gg8) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L46)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Same as above, shouldn't `sed` be used here?
</blockquote></details>

I only found a not-so-trivial solution for this one:

```
sed -i -e '/^extern "C" {$/ {
    :loop
    n
    /^}$/! b loop
    /^}$/ {
        N
        t reset_condition_flags
        :reset_condition_flags
        s/}\nextern "C" {//
        t loop
    }
}' "$BINDING_PATH"
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by jvff** [comment]
Reviewed 3 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[nftnl-sys/src/nftnl_1_0_6.rs, line 0 at r2](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAn6qKn554F_G1BXHH7:-LAn6qKn554F_G1BXHH8:bakkzle) ([raw file](https://github.com/mullvad/nftnl-rs/blob/993cf29280a380a86d8d4de7cd10978edf3ef64d/nftnl-sys/src/nftnl_1_0_6.rs#L0)):*
When I ran `./generate_bindings.sh` for the `1.0.6` version it failed with an error:

```
libnftnl.h:6:10: fatal error: 'libnftnl/object.h' file not found
```

Removing the `#include <libnftnl/object.h>` line from `libnftnl.h` allowed it complete successfully, but a lot of stuff was missing from the generated file compared to the versioned file.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by faern** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[nftnl-sys/generate_bindings.sh, line 42 at r1](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmUDfVEjkVhbQVdmDd:-LAnBNVw6qvIC0XuU3Cf:bxxwbs2) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L42)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Ok, here's the solution I found:

```
sed -i -e '/^pub struct .* {$/ {
    N;N
    s/ {\n *_unused: \[u8; 0\],\n}/(c_void);\n/
}' "$BINDING_PATH"
```
</blockquote></details>

I saw these type of solutions online as well. But they were so unreadable that I ignored them :sweat_smile: But now I can copy paste your solutions as they seem to work perfectly. Awesome, thanks :)

---

*[nftnl-sys/src/nftnl_1_0_6.rs, line  at r2](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAn6qKn554F_G1BXHH7:-LAn9__i2L8C7sgL5uBR:b49tcmz) ([raw file](https://github.com/mullvad/nftnl-rs/blob/993cf29280a380a86d8d4de7cd10978edf3ef64d/nftnl-sys/src/nftnl_1_0_6.rs#L)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

When I ran `./generate_bindings.sh` for the `1.0.6` version it failed with an error:

```
libnftnl.h:6:10: fatal error: 'libnftnl/object.h' file not found
```

Removing the `#include <libnftnl/object.h>` line from `libnftnl.h` allowed it complete successfully, but a lot of stuff was missing from the generated file compared to the versioned file.
</blockquote></details>

Really good find. Seems that 1.0.6 did not have this file. For me it must have picked it up from my default install of libnftnl I had in my path. I'll re-generate it without that one.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by faern** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[nftnl-sys/src/nftnl_1_0_6.rs, line  at r2](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-LAn6qKn554F_G1BXHH7:-LAnBdmH02fzqPe83iXM:b6n7l32) ([raw file](https://github.com/mullvad/nftnl-rs/blob/993cf29280a380a86d8d4de7cd10978edf3ef64d/nftnl-sys/src/nftnl_1_0_6.rs#L)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Really good find. Seems that 1.0.6 did not have this file. For me it must have picked it up from my default install of libnftnl I had in my path. I'll re-generate it without that one.
</blockquote></details>

So it will still not work for <1.0.7 without manual change. It does not feel prioritized to spend time on automating. Now the bindings should be more correct at least I hope.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by jvff** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/nftnl-rs/2#-:-LAngDcnE0JLrjDiF5Qr:bnfp4nl)*

**Comment by faern** [comment]
Since Andrei is going on vacation I changed to Emils as the second reviewer.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2#-:-LAqZhi26Hg6n88Cr4VQ:bmjjuh4)*

**Comment by pronebird** [comment]
Reviewed 7 of 9 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[nftnl-sys/generate_bindings.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmULbc7fbmk4hEnrwo:-LAr0MM8AVyLaef4aFjz:b-m4jug7) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L46)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I only found a not-so-trivial solution for this one:

```
sed -i -e '/^extern "C" {$/ {
    :loop
    n
    /^}$/! b loop
    /^}$/ {
        N
        t reset_condition_flags
        :reset_condition_flags
        s/}\nextern "C" {//
        t loop
    }
}' "$BINDING_PATH"
```
</blockquote></details>

I question if any of this is really necessary. But if you think it's safe enough I am fine with that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by pinkisemils** [comment]
Reviewed 7 of 9 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[nftnl-sys/generate_bindings.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmULbc7fbmk4hEnrwo:-LAr6eBm5kblggyWcjSz:b-sa8dhx) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L46)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I question if any of this is really necessary. But if you think it's safe enough I am fine with that.
</blockquote></details>

I follow Andrei's sentiment here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by jvff** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[nftnl-sys/generate_bindings.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmULbc7fbmk4hEnrwo:-LAr6YUb-Kmq7x89qAEe:b-cloi9i) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L46)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I follow Andrei's sentiment here.
</blockquote></details>

IMHO it's a good idea to have consistent reproducible generated code, to avoid any build differences due to any manual inconsistencies. It would be more elegant and maintainable to have a clean script to do the substitutions, but I don't think it's worth the effort. As long as the command is the same for every execution, the goal was achieved. If we ever need to change or maintain these types of changes, then we can certainly refactor it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[nftnl-sys/generate_bindings.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmULbc7fbmk4hEnrwo:-LArEsWa9JdHn5FO-LTz:b-f9nzah) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L46)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

IMHO it's a good idea to have consistent reproducible generated code, to avoid any build differences due to any manual inconsistencies. It would be more elegant and maintainable to have a clean script to do the substitutions, but I don't think it's worth the effort. As long as the command is the same for every execution, the goal was achieved. If we ever need to change or maintain these types of changes, then we can certainly refactor it.
</blockquote></details>

It is indeed not required to remove the superfluous `extern "C"` blocks. It works fine with them. It's mostly that the generated bindings become many hundred lines shorter and more readable if they are removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[nftnl-sys/generate_bindings.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmULbc7fbmk4hEnrwo:-LArdQJTBa_sAQ90oBBc:b-mwnvig) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It is indeed not required to remove the superfluous `extern "C"` blocks. It works fine with them. It's mostly that the generated bindings become many hundred lines shorter and more readable if they are removed.
</blockquote></details>

It would be great if `bindgen` knew how to group C exports.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by pronebird** [comment]
Reviewed 1 of 9 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[nftnl-sys/generate_bindings.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/2#-LAmULbc7fbmk4hEnrwo:-LArnWRn1cqah9WY5cP1:bxpsyeu) ([raw file](https://github.com/mullvad/nftnl-rs/blob/57d7ede88db27ceba5a75146ebdf78a7c51a9cb8/nftnl-sys/generate_bindings.sh#L46)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

It would be great if `bindgen` knew how to group C exports.
</blockquote></details>

I have asked about this on IRC, or maybe in an github issue, can't remember. Anyway, the response was that it would require some restructuring internally in bindgen as each item it's emitting is stored separately in memory and when emitted it's emitted with surrounding `extern "C" {...}`. Basically they welcomed patches fixing this, but none of them had it as any priority since it does not affect the actual binding in any way more than visually.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/2)*

**Pull request merged**
