### PR TITLE
More examples and link layer functionality 

### PR DESCRIPTION
**Pull request by faern**
I realized some of the generated `README` documentation was outdated. Then I also felt I should elaborate a tiny bit on how the crate was developed and why it might have quirks and flaws.

Then I realized we already had commented out code for checking link layer payloads. So I uncommented this and wrote an example to test if it worked. While doing so I needed access to the `iiftype` metadata to be allowed to even check link layer payloads. And when reading the header file for the metadata attributes I realized there were more fun and useful attributes available, so I implemented the random one when I was at it, it can be useful at times.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/18)

### CODE REVIEW

**Review by jvff — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/18)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @jvff)

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/18)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[nftnl/examples/filter-ethernet.rs, line 10 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/18#-LMmNUSC5PBG2o_A_YFA:-LMmNUSD7zizzuojFL06:b-sruxk9) ([raw file](https://github.com/mullvad/nftnl-rs/blob/f2713838049e3b28b358777b7430705decc03a4a/nftnl/examples/filter-ethernet.rs#L10)):*
> ```Rust
> //! After running this example, the output should be the following:
> //! ```ignore
> //! 
> ```

Will this be added later?
___
*[nftnl/examples/filter-ethernet.rs, line 63 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/18#-LMmd9cH0F9YN72jJBpl:-LMmd9cH0F9YN72jJBpm:b-oj31o7) ([raw file](https://github.com/mullvad/nftnl-rs/blob/f2713838049e3b28b358777b7430705decc03a4a/nftnl/examples/filter-ethernet.rs#L63)):*
> ```Rust
>     // Drop the matching packets.
>     block_ethernet_rule.add_expr(&nft_expr!(verdict drop))?;
>     
> ```

I think there are some empty spaces here?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/18)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @jvff and @faern)

___
*[nftnl/examples/filter-ethernet.rs, line 10 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/18#-LMmNUSC5PBG2o_A_YFA:-LMmilGN7PKIVPPqMgrv:b-1amfp7) ([raw file](https://github.com/mullvad/nftnl-rs/blob/f2713838049e3b28b358777b7430705decc03a4a/nftnl/examples/filter-ethernet.rs#L10)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Will this be added later?
</blockquote></details>

Oops, forgot it! Fixed.
___
*[nftnl/examples/filter-ethernet.rs, line 63 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/18#-LMmd9cH0F9YN72jJBpl:-LMmin8jCpo7G5brIpwC:b-uxyvj4) ([raw file](https://github.com/mullvad/nftnl-rs/blob/f2713838049e3b28b358777b7430705decc03a4a/nftnl/examples/filter-ethernet.rs#L63)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think there are some empty spaces here?
</blockquote></details>

Good catch. Must have forgotten to check `git show` on my commit.

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/18)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[nftnl/examples/filter-ethernet.rs, line 11 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/18#-LMmm1RxB9_7nvOHwleg:-LMmm1RxB9_7nvOHwleh:bpp3jky) ([raw file](https://github.com/mullvad/nftnl-rs/blob/78115c700ac4bd0e9db01ad12c587cd0aabfb91d/nftnl/examples/filter-ethernet.rs#L11)):*
> ```Rust
> //! ```ignore
> //! table inet example-filter-ethernet {
> //! 	chain chain-for-outgoing-packets {
> ```

Nit: maybe replace tabs with spaces?

Not important though

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/18)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @jvff and @faern)

___
*[nftnl/examples/filter-ethernet.rs, line 10 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/18#-LMn3rwi3N2jsoPROBg5:-LMn3rwi3N2jsoPROBg6:bazmhk4) ([raw file](https://github.com/mullvad/nftnl-rs/blob/f2713838049e3b28b358777b7430705decc03a4a/nftnl/examples/filter-ethernet.rs#L10)):*
> ```Rust
> //! After running this example, the output should be the following:
> //! ```ignore
> //! 
> ```

Doh. Just copy pasted the output. Strange the `add-rules` example did not suffer from the same fate...

A I know why. For `add-rules` I copied the output from a `watch nft list ruleset` proces running. And `watch` replaces all tabs with spaces :man_shrugging: 

Anyway, fixed.

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/18)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[nftnl/examples/filter-ethernet.rs, line 10 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/18#-LMn3rwi3N2jsoPROBg5:-LMn5MG0DOHhz5Dkz5dI:bcc2j4n) ([raw file](https://github.com/mullvad/nftnl-rs/blob/f2713838049e3b28b358777b7430705decc03a4a/nftnl/examples/filter-ethernet.rs#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Doh. Just copy pasted the output. Strange the `add-rules` example did not suffer from the same fate...

A I know why. For `add-rules` I copied the output from a `watch nft list ruleset` proces running. And `watch` replaces all tabs with spaces :man_shrugging: 

Anyway, fixed.
</blockquote></details>

Cool, didn't know `watch` did that!

**Pull request merged**
