### PR TITLE
Update `CHANGELOG.md` with missing changes since last release

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR adds missing changelog items since the last release was made in preparation of a new release.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/69)

### CODE REVIEW

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/69)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`CHANGELOG.md` line 20 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/69#-O787LCF3zGOda-x0dUj:-O787LCF3zGOda-x0dUk:bge44sm) ([raw file](https://github.com/mullvad/nftnl-rs/blob/6272cf4ed06b60611e9f5000648bbf98a9c78394/CHANGELOG.md#L20)):*
> ```Markdown
> ### Added
> - Implement `Default` for `nftnl::batch::Batch`.
> - Add support for Raw payload expressions: https://github.com/mullvad/nftnl-rs/pull/52.
> ```

We usually don't link to PRs, and you do it only for one out of many additional entries here. What is the motivation for that?

If we are going to reference PRs, my opinion is that `#52` would be enough. Way shorter. I have seen that format in a bunch of changelogs, but I don't think I have seen people use the full URL.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/69)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`CHANGELOG.md` line 20 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/69#-O787LCF3zGOda-x0dUj:-O78Abnl7qG2S1aFcjcK:b-j7j0rv) ([raw file](https://github.com/mullvad/nftnl-rs/blob/6272cf4ed06b60611e9f5000648bbf98a9c78394/CHANGELOG.md#L20)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We usually don't link to PRs, and you do it only for one out of many additional entries here. What is the motivation for that?

If we are going to reference PRs, my opinion is that `#52` would be enough. Way shorter. I have seen that format in a bunch of changelogs, but I don't think I have seen people use the full URL.
</blockquote></details>

It was just for context, as I didn't think this changelog entry provided did that by itself. The link could very well be removed, not providing it would align stylistically with the rest of the changelog.

As for shortening the reference: It will be rendered as `#52` in GitHub's markdown renderer, so it will looks nice & neat when browsing the changelog via GitHub. And I think providing the full link is more helpful for those who want to track the change.

**Review by faern — APPROVED** [review]
Nit: This fix could be mentioned, since it does fix a bug: `e51fe76 Remove expect statments from nft_set macro`

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/69#-:-O78eZ562UfebdL19JKi:bpcwhdy)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — COMMENTED** [review]
Good catch, it should be mentioned! Fixed

> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/69#-:-O78gPE_2iGAupmara26:bzgvsg0)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @faern)

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/69)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
